---
dotfiles_repo: "https://github.com/ekryski/dotfiles.git"
dotfiles_repo_local_destination: "~/Documents/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .vimrc
