---
- hosts: localhost
  user: vagrant
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - homebrew
    - dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    # - include: tasks/preferences.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    # This doesn't seem to be working inside of Vagrant
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
      sudo: yes
