---
# TODO: Custom iTerm theme/preferences.

# Sudoers configuration (enables more convenient Vagrant usage).
- name: Copy sudoers configuration into place.
  copy:
    src: files/etc/sudoers
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  sudo: yes
  when: configure_sudoers

# TODO: Configure Sublime Text (see templates/sublime/*).
